name: pproxy server
version: 0.0.11
slug: pproxy
description: pproxy server 
url: https://github.com/IATkachenko/ha-addon-pproxy
arch:
  - aarch64
  - amd64
init: false
stdin: true
map:
  - addon_config:rw
ports:
  80/tcp: 8888
ports_description:
  80/tcp: port to listen
options:
  proxy_scheme: null
  proxy_host: null
  proxy_port: null
  proxy_login:
  proxy_password:
schema:
  proxy_scheme: str
  proxy_host: str
  proxy_port: port
  proxy_login: "str?"
  proxy_password: "str?"
